SolidHome/Controllers/PrivacyController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SolidHome.Localization;

namespace SolidHome.Controllers
{
    [MiddlewareFilter(typeof(LocalizationPipeline))]
    public class PrivacyController : Controller

    {
    public IActionResult Index()
    {
        string viewName = "Index_" + CultureInfo.CurrentCulture.Name;
        return View(viewName);
    }
    }
}

SolidHome/Views/Shared/_Footer.cshtml
 @using System.Globalization
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Mvc.Localization
@using SolidHome.Localization
@using SolidHome.Models
@using SolidHome.Service.Interfaces
@using SolidHome.Utils.Service
@using UnidecodeSharpFork
@inject IHtmlLocalizer<Common> localizer
@inject IDirectionService DirectionService
@inject IHttpContextAccessor httpAccessor
@inject ContactsService ContactsService
@{
    Contacts contacts = ContactsService.GetContacts();
    IEnumerable<SmallDirection> directions = DirectionService.GetAllDirections<SmallDirection>(CultureInfo.CurrentCulture.Name).ToList();

}
<footer>
    <div class="top-footer">
        <div class="own-container">
            <div class="row footer-row">
                <div class="footer-quick col-lg-3 col-md-6 col-sm-6 pl-0">
                    <p class="footer-title sub-tittle_ulight_18">@localizer["Subscribe"]</p>
                    <ul class="footer-nav p-0">
                        <li>
                            <div class="input-group footer-email-form">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="@localizer["Email"]"
                                           aria-label="@localizer["Email"]" aria-describedby="btnGroupAddon2">
                                    <span class="input-group-addon" id="btnGroupAddon2">
                                        <i class="icons icon-submit"></i>
                                    </span>
                                </div>
                            </div>
                        </li>
                        <li class="BottomToTop social-icons-block">
                            <a class="social-icons d-flex thin-tittle-13" href="https://www.facebook.com/solidhome.ukraine/">
                                <i class="icons IconFb m-auto"></i>
                            </a>
                            <a class="social-icons d-flex thin-tittle-13" href="https://www.linkedin.com/company/solidhome-ua/">
                                <i class="icons IconIn m-auto"></i>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="footer-quick col-lg-2 col-md-6  col-sm-6 pt-lg-0 pt-md-4 text-right text-lg-left">
                    <p class="footer-title sub-tittle_18 toupc">@localizer["Contacts"]</p>
					<ul class="footer-contact p-0 mt-md-2">
						<li>
							<span>@Html.Raw(contacts.Address.Find(c => c.Language == CultureInfo.CurrentCulture.Name).Text)</span>
						</li>
						<li class="m-0">
							<span>(032)-232-83-09</span>
						</li>
						<li class="m-0">
							<span>(063)-268-52-28</span>
						</li>
						<li class="m-0">
							<span>(044)-500-37-55</span>
						</li>
						<li class="m-0">
							<span>(067)-332-26-03</span>
						</li>
						<li>
							<span>@Html.Raw(contacts.Email)</span>
						</li>
					</ul>
                </div>
                <div class="footer-quick col-lg-2 col-md-4 col-sm-4">
                    <p class="footer-title sub-tittle_18 toupc">@localizer["QuickAccess"]</p>
                    <ul class="footer-nav p-0 mt-md-2">
                        <li><a asp-protocol="https" asp-controller="Home" asp-action="Index" class="thin-tittle-13">@localizer["Main"]</a></li>
                        <li><a asp-protocol="https" asp-controller="catalog" asp-action="Index" class="thin-tittle-13">@localizer["Catalog"]</a></li>
                        <li><a asp-protocol="https" asp-controller="news" asp-action="Index" class="thin-tittle-13">@localizer["News"]</a></li>
                        <li><a asp-protocol="https" asp-controller="contacts" asp-action="Index" class="thin-tittle-13">@localizer["Contacts"]</a></li>
                    </ul>
                </div>
                <div class="footer-quick col-lg-4 col-md-8 col-sm-8">
                    <p class="footer-title sub-tittle_18 toupc">@localizer["Catalog"]</p>
                    <ul class="footer-directions p-0 mt-md-2">
                        @foreach (var direction in directions)
                        {
                            <li><a asp-protocol="https" asp-controller="catalog" asp-action="catalogItem" asp-route-url="@direction.Url" class="thin-tittle-13">@Html.Raw(direction.Title)</a></li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="down-footer">
        <div class="own-container">
            <div class="row footer-down-row">
                <div class="col-lg-4 col-md-4 col-6 pl-0 madeBy down-footer-item">
                    SOLIDHOME © 2018. All Rights Reserved.
                </div>
                <div class="col-lg-4 col-md-4 col-6 text-right madeBy pr-0 down-footer-item">
                    Website by <a href="http://www.solidbrain.com.ua" class="color-light"><u>SOLID BRAIN</u></a>
                </div>
            </div>
        </div>
    </div>
</footer>

SolidHome/Views/Shared/_Header.cshtml
@using System.Globalization
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Mvc.Localization
@using SolidHome.Localization
@using SolidHome.Models
@using SolidHome.Service.Interfaces
@inject IHtmlLocalizer<Common> localizer
@inject IHttpContextAccessor httpAccessor
@inject IDirectionService DirectionService
@{
    var directions = DirectionService.GetAllDirections<SmallDirection>(CultureInfo.CurrentCulture.Name).ToList();
}
<header class="transparent-container own-container">
    <div class="top-header">
        <nav class="navbar navbar-expand-lg navbar-dark ">
            <a class="navbar-brand" asp-protocol="https" asp-controller="home" asp-action="index"><img src="~/images/Logo/LogoLight.svg" alt="Logo" /></a>
            <button class="navbar-toggler" type="button" id="nav-icon">
                <span></span>
                <span></span>
                <span></span>
            </button>
            <div class="navbar-collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link toupc" asp-protocol="https" asp-controller="home" asp-action="Index" data-active="dark">@localizer["Main"]</a>
                    </li>
                    <li class="nav-item catalog-drop">
                        <a class="nav-link toupc" asp-protocol="https" asp-controller="catalog" asp-action="index" data-active="light">@localizer["Catalog"]<i class="icons icon-drop"></i></a>
                        <div class="dropdown-content">
                            @foreach (var direction in directions)
                            {
                                <a class="dropdown-item sub-tittle_18" asp-protocol="https" asp-controller="Catalog" asp-action="CatalogItem" asp-route-url="@direction.Url">@Html.Raw(direction.Title)</a>
                            }
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link toupc" asp-protocol="https" asp-controller="works" asp-action="index" data-active="light">@localizer["Works"]</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link toupc" asp-protocol="https" asp-controller="news" asp-action="Index" data-active="light">@localizer["News"]</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link toupc" asp-protocol="https" asp-controller="contacts" asp-action="Index" data-active="light">@localizer["Contacts"]</a>
                    </li>
                    <li class="nav-item">
                        <p class="nav-link toupc" data-active="light">(063) 268 52 28</p>
                    </li>
                </ul>
            </div>
            @Html.Partial("_Languages")
        </nav>
    </div>
</header>

SolidHome/Views/Shared/_Languages.cshtml
@inject IHttpContextAccessor httpAccessor
@using System.Globalization
@using Microsoft.AspNetCore.Http
@{
    string currentController = ViewContext.RouteData.Values["Controller"].ToString();
    string currentAction = ViewContext.RouteData.Values["Action"].ToString();
}


<div class="lang nav-item">
    <a class="nav-link" asp-protocol="https" asp-controller=@currentController asp-action=@currentAction asp-route-lang="@(CultureInfo.CurrentCulture.Name == "ru" ? "" : "ru")">
        @(CultureInfo.CurrentCulture.Name == "uk" ? "РУС" : "УКР")
    </a>
</div>

SolidHome/Views/Shared/_Layout.cshtml
@using Microsoft.ApplicationInsights.AspNetCore.Extensions
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Mvc.Localization
@using SolidHome.Localization
@inject IHtmlLocalizer<Common> localizer
@inject IHttpContextAccessor httpContext
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @RenderSection("Meta", false)
    @RenderSection("Links", false)
    @if (IsSectionDefined("Title"))
    {
        @RenderSection("Title")
    }
    else
    {
        <title>@ViewData["Title"] - SolidHome</title>
    }
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css">
    <link rel="alternate" hreflang="@localizer["HrefLang"]" href="@httpContext.HttpContext.Request.GetUri()" />
    <link rel="shortcut icon" type="image/x-icon" href="~/images/smallIco.png" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/slick-1.8.0/slick/slick.css">
    <link rel="stylesheet" type="text/css" href="~/lib/slick-1.8.0/slick/slick-theme.css">
    @*<link rel="stylesheet" href="~/css/minified/sitecss.min.css" />*@
    @*<link rel="stylesheet" href="~/css/style.css" />*@
    @*<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.0/slick.min.css">
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.0/slick-theme.min.css">*@

</head>
<body>

    <script>
        window.fbAsyncInit = function () {
            FB.init({
                appId: '882276045287716',
                xfbml: true,
                version: 'v2.12'
            });
            FB.AppEvents.logPageView();
        };

        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) { return; }
            js = d.createElement(s); js.id = id;
            js.src = "https://connect.facebook.net/ru-RU/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    @if (IsSectionDefined("Header"))
    {
        @RenderSection("Header")
    }
    else
    {
        @Html.Partial("_Header")
    }

    <div id="content-body">
        @RenderBody()
    </div>
    @Html.Partial("_Footer")

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.0/slick.min.js"></script>
    @*<script src="~/js/allscripts.min.js" asp-append-version="true"></script>*@
    <script src="~/js/shared.js"></script>
        <script src="~/js/script.js"></script>
        <script src="~/js/slick.js"></script>
<script src="~/js/order.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script type='text/javascript'>

    window.cookieconsent.initialise({
        "palette": {
            "popup": {
                "background": "#000",
                "opacity": 0.7
            },
            "button": {
                "background": "darkgreen"
            }

        },
        "type": "opt-in",
        "content": {
            "message": "@localizer["PolicyMessage"]",
            "link": "@localizer["PolicyHref"]",
            "deny": "@localizer["PolicyDeny"]",
            "allow" : "@localizer["PolicyAgree"]",
            "href": "@Url.Action("Index", "Privacy")"
        },
        onInitialise: function (status) {
            (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)
                [0]; a.async = 1; a.src = g;
                m.parentNode.insertBefore(a, m);
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
            var type = this.options.type;
            var didConsent = this.hasConsented();
            if (didConsent) {
                // enable cookies
                ga('require', 'displayfeatures');
                ga('set', 'anonymizeIp', undefined);
                ga('create', 'UA-57261022-1', 'auto');
                ga('set', 'forceSSL', true);
            } else {
                // disable cookies
                ga('set', 'displayFeaturesTask', null);
                ga('set', 'anonymizeIp', true);
            }
            ga('send', 'pageview');
        },

        onStatusChange: function (status, chosenBefore) {
            (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)
                [0]; a.async = 1; a.src = g;
                m.parentNode.insertBefore(a, m);
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
            var type = this.options.type;
            var didConsent = this.hasConsented();
            if (didConsent) {
                // enable cookies
                ga('require', 'displayfeatures');
                ga('set', 'anonymizeIp', undefined);
                ga('create', 'UA-116921468-1', 'auto');
                ga('set', 'forceSSL', true);
            } else {
                // disable cookies
                ga('set', 'displayFeaturesTask', null);
                ga('set', 'anonymizeIp', true);
            }
            ga('send', 'pageview');
        },

        onRevokeChoice: function () {
            (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)
                [0]; a.async = 1; a.src = g;
                m.parentNode.insertBefore(a, m);
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
            var type = this.options.type;
            if (type == 'opt-in') {
                // disable cookies
                ga('set', 'displayFeaturesTask', null);
                ga('set', 'anonymizeIp', true);
            }
            if (type == 'opt-out') {
                // enable cookies
                ga('require', 'displayfeatures');
                ga('set', 'anonymizeIp', undefined);
                ga('create', 'UA-116921468-1', 'auto');
                ga('set', 'forceSSL', true);
            }
            ga('send', 'pageview');
        }
    });

</script> 

 <script src="~/js/minified/sitejs.min.js"></script>
    <!-- BEGIN JIVOSITE CODE {literal} -->
    <script type='text/javascript'>
        (function () {
            var widget_id = '9nSY5SBeJL'; var d = document; var w = window; function l() {
                var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = '//code.jivosite.com/script/widget/' + widget_id; var ss = document.getElementsByTagName('script')[0]; ss.parentNode.insertBefore(s, ss);
            } if (d.readyState == 'complete') { l(); } else { if (w.attachEvent) { w.attachEvent('onload', l); } else { w.addEventListener('load', l, false); } }
        })();</script>
    <!-- {/literal} END JIVOSITE CODE -->
    @RenderSection("Scripts", required: false)
</body>
</html>