SolidHome/Areas/Admin/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SolidHome.Service.Interfaces;

namespace SolidHome.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class ReviewController : Controller
    {
        private readonly IReviewService _reviewService;

        public ReviewController(IReviewService reviewService)
        {
            _reviewService = reviewService;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

SolidHome/Areas/Admin/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using SolidHome.Localization
@inject IHtmlLocalizer<Common> localizer
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SolidHome</title>

    <environment include="Development">
        @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />*@
        <link rel="stylesheet" href="~/css/admin/minified/admincss.min.css" asp-append-version="true" />
        <link rel="stylesheet" type="text/css" id="u0" href="https://cloud.tinymce.com/stable/skins/lightgray/skin.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/admin/minified/admincss.min.css" asp-append-version="true" />
        <link rel="stylesheet" type="text/css" id="u0" href="https://cloud.tinymce.com/stable/skins/lightgray/skin.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
    </environment>
</head>
<body>
    <div class="row">
        @Html.Partial("_SideBar")
        <div class="col-lg-10 main-content">
            @RenderBody()
        </div>
    </div>
    <environment include="Development">
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
                crossorigin="anonymous"></script>
        @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
        <script src="https://cdn.tinymce.com/4/tinymce.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/bootstrap.min.js"
                integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        @*<script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>*@
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>

        <script src="https://cdn.tinymce.com/4/tinymce.min.js"></script>
        @*<script src="~/lib/multifile/jquery.multifile.js"></script>
        <script src="~/lib/toastr/jquery.toaster.js"></script>
        <script src="~/js/admin/shared.js"></script>
        <script src="~/js/admin/contacts.js"></script>
        <script src="~/js/admin/news.js"></script>
        <script src="~/js/admin/product.js"></script>
        <script src="~/js/admin/remove-item.js"></script>*@
        <script src="~/js/admin/minified/adminjs.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="//code.jquery.com/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
        <script src="https://cdn.tinymce.com/4/tinymce.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/bootstrap.min.js"
                integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        @*<script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>*@
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
        <script src="~/js/admin/minified/adminjs.min.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

SolidHome/Areas/Admin/Views/Shared/_SideBar.cshtml
<div class="col-lg-2 left-menu">
    <a class="navbar-brand" href="http://beta.solidhome.com.ua"><img src="~/images/admin/Littlelogo.png" alt="Logo"></a>
    <ul class="menu-items">
        <li class="sub-tittle_18 active-menu-item">
            <a class="catalog-items" asp-area="admin" asp-controller="news" asp-action="index">
                <i class="icons newsIcon"></i>
                <p>Новини</p>
            </a>
        </li>
        <li class="sub-tittle_18">
            <a class="catalog-items" asp-area="admin" asp-controller="catalog" asp-action="index">
                <i class="icons catalogIcon"></i>
                <p>Каталог</p>
            </a>
        </li>
        <li class="sub-tittle_18">
            <a class="catalog-items" asp-area="admin" asp-controller="works" asp-action="index">
                <i class="icons catalogIcon"></i>
                <p>Роботи</p>
            </a>
        </li>
        <li class="sub-tittle_18">
            <a class="catalog-items" asp-area="admin" asp-controller="Review" asp-action="index">
                <i class="icons directIcon"></i>
                <p>Відгуки</p>
            </a>
        </li>

        <li class="sub-tittle_18">
            <a class="catalog-items" asp-area="admin" asp-controller="contacts" asp-action="index">
                <i class="icons contactIcon"></i>
                <p>Контакти</p>
            </a>
        </li>
        <li class="sub-tittle_18">
            <a class="catalog-items" asp-area="admin" asp-controller="mails" asp-action="index">
                <i class="icons postIcon"></i>
                <p>Листи</p>
            </a>
        </li>
        <li class="sub-tittle_18">
            <a class="catalog-items" asp-area="admin" asp-controller="order" asp-action="index">
                <i class="icons userContact"></i>
                <p>Замовлення</p>
            </a>
        </li>
    </ul>
    <a href="/account/logout" class="log-out-block sub-tittle_18"><i class="icons logOutIcon"></i>
        <p>Вийти</p></a>
</div>